# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5964c4c7f4f50878804a26e8fb6487d7bc9f02406e97ea47ebb6b673ddc1aeebdce46a96cb6cb12da048880ae839029e19bb97eff7494258729b9ad2df05c9d7

test:
  secret_key_base: 99c3acc9a61b08f4e48cae5296a2b61fb120192859c2176626b3e0a547a7191aee4871a3fca40d920d7cccd54bff27d8682ae46039b1d0e0d15aff39dc73a86b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
